# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://www.aravind-kumar.net"
defaultContentLanguage = "en"

enableRobotsTXT = true
summaryLength = 0

[params]
  dateFormat = "2 January 2006"

[params.author]
  name = "Aravind Kumar Kamaraj"
  bio = "Computational neuroscientist specialising in mechanistic modelling and EEG analyses"
  image = "img/author.jpg"
  links = [
      { email = "mailto:aravindkumark@outlook.com" },
      { linkedin = "https://www.linkedin.com/in/aravind-kumar-kamaraj/" },
      { x-twitter = "https://x.com/AravindKumar264" },
      { google-scholar = "https://scholar.google.com/citations?user=NQZm830AAAAJ&hl=en" },
      { orcid = "https://orcid.org/0000-0001-7926-1120"},
      { researchgate = "https://www.researchgate.net/profile/Aravind-Kumar-2"},
      { github = "https://github.com/Aero264" },
  ]

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


